### ISSUE TITLE
Daffodil doesn't unparse the example xml infoset

### ISSUE THREAD

**Issue by kristiank** [keeleleek/dfdl-praat-textgrid-schema#1]
Even though Daffodil itself says this is a bug, I think it could be a problem in the XML Schema definition. Perhaps using ```xs:decimal``` is not correct.

Daffodil throws the following error message:

```
Filetype="ooTextFile"
Objectclass="TextGrid"

xmin=0
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!   An unexpected exception occurred. This is a bug!   !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

 Please report this bug and help us fix it:

  https://opensource.ncsa.illinois.edu/confluence/display/DFDL/How+to+Report+a+Bug

 Please include the following exception, the command you
 ran, and any input, schema, or tdml files used that led
 to this bug.


Runtime Schema Definition Error: Unparser (ConvertTextDecimalPrim) is not yet implemented.
Schema context: element.xMin. Location line 34 column 8 in file:/home/kristian/Projektid/DFDL/Praat TextGrid/PraatTextGrid.dfdl.xsd. Data Context: byte 52.
	at edu.illinois.ncsa.daffodil.processors.ParseOrUnparseState.SDE(PState.scala:145)
	at edu.illinois.ncsa.daffodil.processors.unparsers.DummyUnparser.unparse(Unparser.scala:119)
	at edu.illinois.ncsa.daffodil.processors.unparsers.Unparser.unparse1(Unparser.scala:63)
	at edu.illinois.ncsa.daffodil.processors.unparsers.SeqCompUnparser$$anonfun$unparse$2.apply(Unparser.scala:106)
	at edu.illinois.ncsa.daffodil.processors.unparsers.SeqCompUnparser$$anonfun$unparse$2.apply(Unparser.scala:104)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at edu.illinois.ncsa.daffodil.processors.unparsers.SeqCompUnparser.unparse(Unparser.scala:104)
	at edu.illinois.ncsa.daffodil.processors.unparsers.Unparser.unparse1(Unparser.scala:63)
	at edu.illinois.ncsa.daffodil.processors.unparsers.SeqCompUnparser$$anonfun$unparse$2.apply(Unparser.scala:106)
	at edu.illinois.ncsa.daffodil.processors.unparsers.SeqCompUnparser$$anonfun$unparse$2.apply(Unparser.scala:104)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at edu.illinois.ncsa.daffodil.processors.unparsers.SeqCompUnparser.unparse(Unparser.scala:104)
	at edu.illinois.ncsa.daffodil.processors.unparsers.Unparser.unparse1(Unparser.scala:63)
	at edu.illinois.ncsa.daffodil.processors.unparsers.DelimiterStackUnparser.unparse(ElementKindUnparsers.scala:223)
	at edu.illinois.ncsa.daffodil.processors.unparsers.Unparser.unparse1(Unparser.scala:63)
	at edu.illinois.ncsa.daffodil.processors.unparsers.StatementElementUnparserBase$$anonfun$unparse$1.apply(StatementElementUnparser.scala:99)
	at edu.illinois.ncsa.daffodil.processors.unparsers.StatementElementUnparserBase$$anonfun$unparse$1.apply(StatementElementUnparser.scala:98)
	at scala.Option.map(Option.scala:145)
	at edu.illinois.ncsa.daffodil.processors.unparsers.StatementElementUnparserBase.unparse(StatementElementUnparser.scala:98)
	at edu.illinois.ncsa.daffodil.processors.unparsers.Unparser.unparse1(Unparser.scala:63)
	at edu.illinois.ncsa.daffodil.processors.unparsers.SequenceCombinatorUnparser.unparse(ElementKindUnparsers.scala:137)
	at edu.illinois.ncsa.daffodil.processors.unparsers.Unparser.unparse1(Unparser.scala:63)
	at edu.illinois.ncsa.daffodil.processors.unparsers.ComplexTypeUnparser.unparse(ElementKindUnparsers.scala:62)
	at edu.illinois.ncsa.daffodil.processors.unparsers.Unparser.unparse1(Unparser.scala:63)
	at edu.illinois.ncsa.daffodil.processors.unparsers.StatementElementUnparserBase$$anonfun$unparse$1.apply(StatementElementUnparser.scala:99)
	at edu.illinois.ncsa.daffodil.processors.unparsers.StatementElementUnparserBase$$anonfun$unparse$1.apply(StatementElementUnparser.scala:98)
	at scala.Option.map(Option.scala:145)
	at edu.illinois.ncsa.daffodil.processors.unparsers.StatementElementUnparserBase.unparse(StatementElementUnparser.scala:98)
	at edu.illinois.ncsa.daffodil.processors.DataProcessor.unparse(Runtime.scala:310)
	at edu.illinois.ncsa.daffodil.processors.DataProcessor.unparse(Runtime.scala:296)
	at edu.illinois.ncsa.daffodil.processors.DataProcessor.unparse(Runtime.scala:274)
	at edu.illinois.ncsa.daffodil.Main$$anonfun$90.apply(Main.scala:910)
	at edu.illinois.ncsa.daffodil.Main$$anonfun$90.apply(Main.scala:910)
	at edu.illinois.ncsa.daffodil.util.Timer$.getTimeResult(Timer.scala:91)
	at edu.illinois.ncsa.daffodil.util.Timer$.getResult(Timer.scala:50)
	at edu.illinois.ncsa.daffodil.Main$.run(Main.scala:910)
	at edu.illinois.ncsa.daffodil.Main$.main(Main.scala:1104)
	at edu.illinois.ncsa.daffodil.Main.main(Main.scala)
```

**Comment by kristiank** [comment]
Works with daffodil-2.0.0-rc2
